# Generated by Django 5.2.17 on 2026-09-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dois_fatores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivototp',
            name='segredo',
        ),
        migrations.AddField(
            model_name='dispositivototp',
            name='segredo_cifrado',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
