# Generated by Django 5.2.17 on 2026-10-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorDeTentativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=64, unique=True)),
                ('valor', models.PositiveIntegerField(default=0)),
                ('expira_em', models.FloatField()),
            ],
            options={
                'verbose_name': 'contador de tentativas',
                'verbose_name_plural': 'contadores de tentativas',
            },
        ),
    ]
