"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    # No lugar de 'django.contrib.admin': o login do admin padrao nao passa
    # pelo segundo fator nem pelo bloqueio de tentativas. Ver
    # usuarios/admin_site.py.
    'usuarios.admin_config.AdminCirculaGovConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',  # runserver_plus, usado só localmente pra testar HTTPS (requisito 3.3)
    'usuarios',
    'dois_fatores',
    'recuperacao_senha',
    'consentimento',
    'alunos',
    'direitos_titular',
    'auditoria',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serve os arquivos estaticos em producao. Com DEBUG=False o Django
    # para de servi-los sozinho, e sem isso o /admin/ fica sem CSS.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'usuarios.middleware.TimeoutAbsolutoMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5432'),
    }
}


PASSWORD_HASHERS = [
    'usuarios.hashers.Argon2PasswordHasherCirculaGov',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

AUTH_USER_MODEL = 'usuarios.Usuario'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'usuarios:inicio'
LOGOUT_REDIRECT_URL = 'login'


SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 30 * 60

TEMPO_MAXIMO_SESSAO_SEGUNDOS = 12 * 60 * 60

SESSION_COOKIE_HTTPONLY = True

# Chave usada pra cifrar o segredo do 2FA em repouso (requisitos 3.4/3.6).
# Fica fora do banco, numa variável de ambiente, igual a SECRET_KEY.
CHAVE_CIFRAGEM_2FA = env('CHAVE_CIFRAGEM_2FA')

# TLS/HTTPS obrigatório em produção, e bloqueio de conexão insegura
# (requisitos 3.1/3.2). Fica atrás do DEBUG pra não travar o
# desenvolvimento local, que roda em HTTP simples.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Atras de proxy reverso quem encerra o TLS e o nginx, entao a
    # requisicao chega na aplicacao como HTTP. Sem este cabecalho o
    # Django nao sabe que a conexao original era segura, o
    # SECURE_SSL_REDIRECT redireciona de novo pra HTTPS e vira laco
    # infinito. O nginx precisa enviar X-Forwarded-Proto.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # O Django 4+ exige a origem declarada pra aceitar POST vindo de
    # HTTPS atras de proxy. Sem isso, login e consentimento falham.
    CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

    # De onde vem o endereco de quem acessa. Atras do nginx o REMOTE_ADDR e
    # o do proprio proxy, e o bloqueio de login por endereco ficaria igual
    # pra todo mundo. O nginx sobrescreve o X-Real-IP com o endereco real,
    # entao o valor nao vem do cliente. Ver docs/DEPLOY.md.
    CABECALHO_IP_DO_CLIENTE = 'HTTP_X_REAL_IP'

    # Em producao o Gunicorn roda com varios workers, e cada processo
    # teria o proprio contador em memoria: 5 tentativas viram 5 por
    # worker. Guardar no banco mantem a contagem unica (requisito 1.11).
    # A tabela e criada com: python manage.py createcachetable
    #
    # MAX_ENTRIES precisa ser alto. O padrao do Django e 300, e ao passar
    # disso ele apaga um terco das entradas por ordem alfabetica da chave,
    # e nao as mais antigas. Com 300, quem tenta senhas contra uma conta
    # zera o proprio bloqueio mandando tentativas com nomes inventados.
    # Entradas vencidas (15 min) saem antes e nao contam pro limite.
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'cache_bloqueio_login',
            'OPTIONS': {'MAX_ENTRIES': 100_000},
        }
    }

# E-mail de recuperação de senha (requisito 2.1).
# Console backend: em vez de mandar e-mail de verdade, escreve no
# terminal onde o servidor está rodando. Serve pra desenvolvimento e
# para gerar evidência nos testes, sem precisar de um servidor SMTP.
# Em desenvolvimento o padrao continua sendo o console, que escreve o
# e-mail no terminal. Em producao as variaveis do .env apontam pra um
# SMTP real, senao a recuperacao de senha nao chega em ninguem.
EMAIL_BACKEND = env(
    'EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env(
    'DEFAULT_FROM_EMAIL', default='nao-responda@circulagov.local')

# Pasta dos logs de seguranca, nao versionada (ver .gitignore).
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

# Chave do HMAC que protege o log contra alteracao (requisito 5.3).
# Separada da CHAVE_CIFRAGEM_2FA: cada chave com uma unica finalidade.
CHAVE_INTEGRIDADE_LOGS = env('CHAVE_INTEGRIDADE_LOGS')

# Configuracao do log de seguranca (issues #30 e #31).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'seguranca': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'seguranca',
        },
        # Assina e encadeia cada linha (ver auditoria/integridade.py).
        # Todo logger filho de "seguranca" passa por aqui automaticamente.
        'arquivo_seguranca': {
            'class': 'auditoria.integridade.HandlerLogIntegro',
            'filename': LOG_DIR / 'seguranca.log',
            'formatter': 'seguranca',
            'chave': CHAVE_INTEGRIDADE_LOGS,
        },
    },
    'loggers': {
        'seguranca': {
            'handlers': ['console', 'arquivo_seguranca'],
            'level': 'INFO',
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Pasta onde o collectstatic junta tudo pro WhiteNoise servir.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# CompressedStaticFilesStorage comprime os arquivos mas nao usa manifesto
# com hash no nome. O manifesto quebra o collectstatic se algum CSS
# referenciar arquivo que nao existe, e aqui a simplicidade vale mais
# que o cache-busting.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
