# Generated by Django 5.2.17 on 2026-09-10 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.CharField(choices=[('cadastro', 'Cadastro e autenticação na plataforma'), ('comunicacoes', 'Comunicações por e-mail sobre empréstimos')], max_length=20)),
                ('versao_termos', models.CharField(default='1.0', max_length=10)),
                ('aceito_em', models.DateTimeField(auto_now_add=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consentimento',
                'verbose_name_plural': 'consentimentos',
                'constraints': [models.UniqueConstraint(condition=models.Q(('revogado_em__isnull', True)), fields=('usuario', 'finalidade'), name='um_consentimento_ativo_por_finalidade')],
            },
        ),
    ]
